RAW_HOSPITALS			= '../../data/raw/hospitals.csv'
RAW_MEDICAL_CENTERS 	= '../../data/raw/medical_centers.csv'
RAW_DEMOGRAPHICS_2016 	= '../../data/raw/IndicadoresDistritos2016.xls'
RAW_DEMOGRAPHICS_2017 	= '../../data/raw/IndicadoresDistritos2017.xls'
RAW_DEMOGRAPHICS_2018 	= '../../data/raw/PANEL_INDICADORES_2018.xls'

SAMUR_2017				= '../../data/processed/Dataset_SAMUR_2017.csv'
SAMUR_2018				= '../../data/processed/Dataset_SAMUR_2018.csv'
SAMUR_2019				= '../../data/processed/Dataset_SAMUR_2019.csv'
DISTRICTS				= '../../data/processed/distritos_municipio_madrid.csv'
MEDICAL_CENTERS_TIMES	= '../../data/processed/medical_centers_times.csv'
SAMUR 					= '../../data/processed/Dataset_SAMUR.csv'
MEDICAL_CENTERS			= '../../data/processed/medical_centers.csv'
HOSPITALS 				= '../../data/processed/hospitals.csv'
HOSPITALS_YAML 			= '../../data/processed/hospitals.yaml'
DEMOGRAPHICS			= '../../data/processed/demographics.csv'
SAMUR_MERGED			= '../../data/processed/Dataset_SAMUR_{0}.csv'